package Model;
// Generated 12/01/2016 05:40:33 PM by Hibernate Tools 4.3.1



/**
 * Guille generated by hbm2java
 */
public class Guille  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private String cargo;
     private String username;
     private String pass;

    public Guille() {
    }

    public Guille(String nombre, String cargo, String username, String pass) {
       this.nombre = nombre;
       this.cargo = cargo;
       this.username = username;
       this.pass = pass;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getCargo() {
        return this.cargo;
    }
    
    public void setCargo(String cargo) {
        this.cargo = cargo;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPass() {
        return this.pass;
    }
    
    public void setPass(String pass) {
        this.pass = pass;
    }




}


